# Generated by Django 5.2.4 on 2025-09-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.PositiveBigIntegerField(max_length=12),
        ),
    ]
