# Generated by Django 5.2.4 on 2025-09-11 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('marcas', '0001_initial'),
        ('produtos', '0004_alter_produto_codigo_barras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=False, max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='marcas.marca'),
        ),
    ]
