# Generated by Django 5.2.4 on 2025-09-16 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0006_alter_produto_categoria_alter_produto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque', models.PositiveIntegerField()),
                ('dt_validade', models.DateField()),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='validades', to='produtos.produto')),
            ],
        ),
    ]
