# Generated by Django 5.2.4 on 2025-09-18 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_categoria_alter_produto_marca'),
        ('validades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validade',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validades', to='produtos.produto'),
        ),
    ]
